[supabase]
url = "https://wfuwrhzjpudshutjuohk.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndmdXdyaHpqcHVkc2h1dGp1b2hrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwMzA5MDgsImV4cCI6MjA2ODYwNjkwOH0.L0UHDRBSkKHreK5qUpKfSP_n2Rv3Gh45l5mslod7wdw"
[cohere]
api_key = "xtBhLSqb5EbmwfQe0ylkrdTNgiIvy7JGbR3JgpJS"
